### ISSUE TITLE
Add Reconnecting for Clients

### ISSUE THREAD

**Issue by dylwhich** [umbc-hackafe/bridgesim#15]
If a client is disconnected, the page must be refreshed to reconnect. The client should automatically connect and resume where it left off.

**Comment by zstewar1** [comment]
There is an onclose event on the websocket object, but that will only fire once when the connection is first lost. You could use it to start an interval or self-rescheduling timeout which repeatedly tries to reconnect the server. On my train project it just attempts to connect to the server once per second any time the web socket variable is null or has status WebSocket.CLOSED.

**Comment by SashaCrofter** [comment]
This seems to have been fixed.
