### ISSUE TITLE
Rotating ship demo doesn't work

### ISSUE THREAD

**Issue by SashaCrofter** [umbc-hackafe/bridgesim#19]
It spits out `TypeError: _glExtensionCompressedTextureS3TC.COMPRESSED_RGBA_S3TC_DXT3_EXT is null` into the console several times a second. I'm running Firefox nightly on Arch.

**Comment by zstewar1** [comment]
Could not reproduce.

Tried both webgl/testingserver.py and server/main.py in both Chrome and Firefox on Fedora. Not using nightly, try another browser maybe?

**Comment by SashaCrofter** [comment]
This turned out to be an issue with my graphics drivers. I had been using `xf86-video-intel-git`, and when I changed back to `xf86-video-intel` and rebooted, it began working.
