### ISSUE TITLE
Buttons on UI are disabled

### ISSUE THREAD

**Issue by thegeekguy** [umbc-hackafe/bridgesim#20]
Going to localhost:9000 yields a page in which the "Pause Rotation" and "Click to test stuff" buttons are greyed out and inoperable. Perhaps a CSS issue?

**Comment by dylwhich** [comment]
Did you run the makefile in the webgl dir? The buttons there should become
functional when the client connects. It's also possible that client updates
broke the index at some point.
 The JS console should tell you what's going on.

**Comment by zstewar1** [comment]
Confirmed. Multiple type errors on the console: undefined is not a function, and cannot read property 'zoomIn' of undefined.

**Comment by zstewar1** [comment]
I got that on Chrome on my laptop, now I just pulled on my desktop, and the buttons were still greyed out, but I didn't see any errors.

**Comment by SashaCrofter** [comment]
This is the result of not modifying CSS classes properly in the latest code. I'll take a look.
