### ISSUE TITLE
Deal with screwy upside down map coordinates

### ISSUE THREAD

**Issue by SashaCrofter** [umbc-hackafe/bridgesim#34]
Canvases assign coordinates from the top left corner, that being the smallest, whereas normal coordinate systems begin from the bottom left.

**Comment by zstewar1** [comment]
Expect this sort of thing while dealing with any graphics system. CRTs
scanned left to right top, to bottom, and its now prety much standard for
displays to place 0,0 at the top left. You'll just have to flip vertically
and translate by the height of the canvas if you want the bottom left.
(Xorg, opengl 2d stuff, gtk, and even absolutely positioned html all use
top left based coordinates).
