### ISSUE TITLE
Invalid syntax for Python 2, but Shebang just uses /usr/bin/python

### ISSUE THREAD

**Issue by zstewar1** [umbc-hackafe/bridgesim#38]
We either need to change things so they work with Python 2 again, or change any shebang lines to target Python 3, preferably "/usr/bin/env python3"

**Comment by SashaCrofter** [comment]
I'm okay with specializing toward Python 3. :+1:

**Comment by dylwhich** [comment]
I believe this was closed in d6d8c6f
