### ISSUE TITLE
Implement Map functionality

### ISSUE THREAD

**Issue by dylwhich** [umbc-hackafe/bridgesim#7]
Until the full 3D client is completed, we can use the map as our primary game screen. This will allow us to actually test the full game functionality.

**Comment by SashaCrofter** [comment]
This was made partially complete by 3295ac962fbf817e0928a7a7a926bbde2b8380f6, 3a4d59b85799a7f01db390a90a69e97ca3f6340b.

**Comment by SashaCrofter** [comment]
This is mostly complete now. Anything extra should be added as a separate issue.
